/**
 * Editable copy for the app. Change strings here to update text across the site.
 */
export const copy = {
  site: {
    title: 'future',
    tabTitle: 'Ancient Wisdom → AI Age',
    description: 'future — start your journey and more.',
    tagline: '',
  },

  nav: {
    home: 'home',
    chart: 'start your journey',
    todayChart: "today's chart",
    influence: 'influences',
    compatibility: 'compatibility',
    dashboard: 'dashboard',
    signIn: 'sign in',
    signOut: 'sign out',
    ariaLabel: 'main navigation',
    themeLight: 'switch to light mode',
    themeDark: 'switch to dark mode',
  },

  influence: {
    title: 'influences',
    subtitle: 'planetary conjunctions this month — when two planets are within 10°.',
    viewBands: 'bands',
    viewLines: 'gaussian',
    viewBandsHint: 'Show influences as filled bands',
    viewLinesHint: 'Show influences as Gaussian bells peaking on conjunction day',
  },

  auth: {
    loginTitle: 'sign in',
    registerTitle: 'create account',
    emailLabel: 'email',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'password',
    passwordPlaceholder: '••••••••',
    nameLabel: 'name (optional)',
    namePlaceholder: 'your name',
    submitLogin: 'sign in',
    submitRegister: 'create account',
    noAccount: "don't have an account?",
    hasAccount: 'already have an account?',
    registerLink: 'create one',
    loginLink: 'sign in',
    signInWithGoogle: 'sign in with Google',
    signInWithGitHub: 'sign in with GitHub',
    signUpWithGoogle: 'sign up with Google',
    signUpWithGitHub: 'sign up with GitHub',
    orContinueWithEmail: 'or continue with email',
    errors: {
      invalidCredentials: 'invalid email or password.',
      generic: 'something went wrong. try again.',
      configTitle: 'Sign-in error',
      configHint: 'Usually this means AUTH_SECRET is missing or wrong. Run: npx auth secret — then add AUTH_SECRET=<the-output> to your .env and restart the dev server.',
      accessDeniedHint: 'Sign-in was denied. For Google/GitHub this usually means the app could not reach the database or create your user. Check: (1) DATABASE_URL and DIRECT_URL in .env, (2) run npx prisma migrate deploy, (3) check the server terminal for “[auth] OAuth signIn callback error”.',
      backToLogin: '← Back to sign in',
    },
  },

  dashboard: {
    title: 'dashboard',
    backToDashboard: 'back to dashboard',
    subtitle: 'saved charts',
    tabCharts: 'charts',
    tabInfluences: 'influences',
    tabAsk: 'ask',
    todayChart: "today's chart",
    newChart: 'new chart',
    myChart: 'my chart',
    addChart: 'add chart',
    otherCharts: 'other charts',
    otherChartsHint: 'e.g. friend, partner, family — add a label when you save.',
    noCharts: 'you have no saved charts yet.',
    noChartsHint: 'calculate a chart and save it with a label to see it here.',
    saveChart: 'save this chart',
    saveToMyChart: 'save as my chart',
    chartLabel: 'chart label',
    chartLabelPlaceholder: "e.g. friend, mom's chart",
    saved: 'saved',
    delete: 'delete',
    view: 'view',
    createdAt: 'saved',
    setAsMyChart: 'set as my chart',
    askPlaceholder: 'Ask anything…',
    askSend: 'Send',
    askError: 'Could not get a reply. Check ANTHROPIC_API_KEY in .env.',
    askEmpty: 'Ask a question above to chat.',
  },

  footer: {
    tagline: '',
    copyright: '© {year} future. made with ☾ in the usa. all rights reserved.',
    moonPhase: 'moon: {phase} · {days} days to {target} moon',
    moonTargetFull: 'full',
    moonTargetNew: 'new',
    links: [
      { label: 'home', href: '/' },
      { label: 'start your journey', href: '/chart' },
      { label: 'influences', href: '/influence' },
      { label: 'compatibility', href: '/compatibility' },
      { label: 'dashboard', href: '/dashboard' },
    ],
  },

  compatibility: {
    title: 'compatibility',
    chart1: 'chart 1',
    chart2: 'chart 2',
    selectSaved: 'saved chart',
    calculateNew: 'calculate new',
    chooseChart: 'choose a chart',
    yourCharts: 'your saved charts',
    noCharts: 'No saved charts. Calculate one above or go to dashboard.',
    planetsInHouses: (name: string) => `${name}'s planets in the other's houses`,
    planet: 'planet',
    sign: 'sign',
    house: 'house',
    explanation: 'meaning',
    score: 'score',
    overall: 'overall compatibility',
    calculateCompatibility: 'calculate compatibility',
    compatibility: 'compatibility',
    scoreHigh: 'High',
    scoreMedium: 'Medium',
    scoreLow: 'Low',
  },

  home: {
    heroIcon: '✦',
    title: 'your cosmic blueprint',
    subtitle:
      'ancient wisdom meets the AI age',
    tagline: '',
    cta: 'calculate my chart',
    features: [
      { icon: '☉', label: 'learn about yourself' },
      { icon: 'handshake', label: 'check compatibility with others' },
    ],
  },

  notFound: {
    title: 'page not found',
    message: 'This page drifted off the chart. Try heading back to your cosmic blueprint.',
    backHome: '← back to home',
  },

  privacy: {
    title: 'privacy policy',
    backHome: '← back to home',
    lastUpdated: 'last updated: march 2026',
    intro: 'future (“we”) respects your privacy. This policy describes how we collect, use, and protect your information when you use our services.',
    sections: {
      collection: 'information we collect',
      use: 'how we use your information',
      sharing: 'sharing your information',
      security: 'security',
      contact: 'contact us',
    },
  },

  terms: {
    title: 'terms of service',
    backHome: '← back to home',
    lastUpdated: 'last updated: march 2026',
    intro: 'Welcome to future. By using our services, you agree to these terms. Please read them carefully.',
    sections: {
      acceptance: 'acceptance of terms',
      use: 'use of the service',
      account: 'accounts',
      content: 'user content',
      contact: 'contact us',
    },
  },

  chart: {
    back: '← back',
    title: 'start your journey',
    titlePrefix: '✦',
    tagline: '',
    birthTime: 'time',
    back15m: '−15m',
    forward15m: '+15m',
    back1h: '−1 hr',
    forward1h: '+1 hr',
    checkTransits: 'check transits',
    deleteChart: 'delete chart',
    transitsTitle: 'transits',
    transitsSubtitle: (dateLabel: string) => `current sky as of ${dateLabel}`,
    transitsTableTitle: 'natal and transits',
    transitsTableNatal: 'natal',
    transitsTableTransits: 'transits',
  },

  today: {
    title: "chart of the moment",
    subtitle: 'current transits in Austin',
    goToToday: 'go back to today',
    prevDay: '1 day before',
    nextDay: '1 day after',
    prevMonth: '1 month before',
    nextMonth: '1 month after',
    prevYear: '1 year before',
    nextYear: '1 year after',
  },

  saveChart: {
    label: 'label for this chart',
    placeholder: "e.g. friend, partner's chart",
    button: 'save chart',
    saveToMyChart: 'save as my chart',
    calculateCompatibility: 'calculate a compatibility',
    saveWithLabel: 'Or save with a label',
    saving: 'saving…',
    success: 'chart saved.',
    signInToSave: 'sign in to save charts',
  },

  form: {
    sectionTitle: 'find your cosmic blueprint',
    dateLabel: 'date of birth',
    timeLabel: 'time of birth',
    timeNotKnown: 'time not known (use 12pm)',
    cityLabel: 'birth city',
    cityNotKnown: 'city not known',
    utcLabel: 'utc offset — adjust if DST applies',
    utcPlaceholder: 'e.g. -5 or +1',
    submit: 'calculate my chart',
    calculating: 'calculating…',
    errors: {
      noDate: 'please enter your birth date.',
      noTime: 'please enter your birth time.',
      noCity: 'please search for and select a birth city.',
      invalidUtc: 'please enter a valid utc offset.',
      invalidYear: 'please use a birth date between 1900 and 2100.',
    },
  },

  chartOptions: {
    sectionTitle: 'add to chart',
    lilith: 'Lilith',
    juno: 'Juno',
    chiron: 'Chiron',
    northNode: 'North Node',
    southNode: 'South Node',
    lotOfFortune: 'Lot of Fortune',
    lotOfSpirit: 'Lot of Spirit',
    lotOfEros: 'Lot of Eros',
    lotOfVictory: 'Lot of Victory',
  },

  citySearch: {
    placeholder: 'e.g. austin',
    search: 'search',
    searching: 'searching…',
    foundPrefix: '✓',
  },

  planetTable: {
    title: 'objects and angles',
    planet: 'planet',
    sign: 'sign',
    degree: 'degree',
    house: 'house',
  },

  ascendant: {
    title: 'ascendant (rising sign)',
    risingSuffix: '— your rising sign',
    mcLabel: 'mc (midheaven):',
    houseLabel: (n: number) => `house ${n}:`,
  },

  noAnglesNote:
    '(this chart has no ascendant - and other angles - since the birth time and/or birth place are needed to calculate these angles)',
} as const;
