import predict from '@/data/predict.json';

/**
 * Editable copy for the app. Change strings here to update text across the site.
 * Predict page strings (hero + question cards) live in `data/predict.json`.
 */
export const copy = {
  site: {
    title: 'future',
    tabTitle: 'Ancient Wisdom → AI Age',
    description: 'future — create a chart and more.',
    tagline: '',
  },

  nav: {
    home: 'home',
    predict: 'predict',
    chartOfMoment: 'current sky',
    chart: 'create a chart',
    todayChart: "today's chart",
    influence: 'influences',
    compatibility: 'compatibility',
    dashboard: 'dashboard',
    signIn: 'sign in',
    signOut: 'sign out',
    ariaLabel: 'main navigation',
    themeLight: 'switch to light mode',
    themeDark: 'switch to dark mode',
  },

  influence: {
    title: 'influences',
    subtitle:
      'major sky aspects in this range — conjunction, opposition, trine, square, and sextile, each within default orbs. Toggle which aspects appear on the plot.',
    aspectsLabel: 'Plot aspects',
    aspectsGroupAria: 'Aspect types to include on the influence plot',
    noAspectsSelected: 'Select at least one aspect type to show on the plot.',
    viewBands: 'aspect bands',
    viewLines: 'aspect gaussians',
    viewBandsHint: 'Show influences as filled bands',
    viewLinesHint: 'Show influences as Gaussian bells peaking on exact aspect days',
    emptyRange: 'No matching aspects in this date range (within each selected aspect’s default orb).',
  },

  nextConjunctions: {
    title: 'upcoming aspects',
    /** Per-aspect carousel slide title and dot button aria label */
    slideByAspect: {
      conjunction: { title: 'next conjunctions', goToAria: 'show conjunction table' },
      opposition: { title: 'next oppositions', goToAria: 'show opposition table' },
      trine: { title: 'next trines', goToAria: 'show trine table' },
      square: { title: 'next squares', goToAria: 'show square table' },
      sextile: { title: 'next sextiles', goToAria: 'show sextile table' },
    },
    carouselPrevious: 'previous slide',
    carouselNext: 'next slide',
  },

  auth: {
    loginTitle: 'sign in',
    registerTitle: 'create account',
    emailLabel: 'email',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'password',
    passwordPlaceholder: '••••••••',
    nameLabel: 'name (optional)',
    namePlaceholder: 'your name',
    submitLogin: 'sign in',
    submitRegister: 'create account',
    noAccount: "don't have an account?",
    hasAccount: 'already have an account?',
    registerLink: 'create one',
    loginLink: 'sign in',
    signInWithGoogle: 'sign in with Google',
    signInWithGitHub: 'sign in with GitHub',
    signUpWithGoogle: 'sign up with Google',
    signUpWithGitHub: 'sign up with GitHub',
    orContinueWithEmail: 'or continue with email',
    errors: {
      invalidCredentials: 'invalid email or password.',
      generic: 'something went wrong. try again.',
      configTitle: 'Sign-in error',
      configHint: 'Usually this means AUTH_SECRET is missing or wrong. Run: npx auth secret — then add AUTH_SECRET=<the-output> to your .env and restart the dev server.',
      accessDeniedHint: 'Sign-in was denied. For Google/GitHub this usually means the app could not reach the database or create your user. Check: (1) DATABASE_URL and DIRECT_URL in .env, (2) run npx prisma migrate deploy, (3) check the server terminal for “[auth] OAuth signIn callback error”.',
      backToLogin: '← Back to sign in',
    },
  },

  dashboard: {
    title: 'dashboard',
    yourChartAndTransits: 'your chart and transits',
    backToDashboard: 'back to dashboard',
    subtitle: 'saved charts',
    tabCharts: 'charts',
    tabInfluences: 'influences',
    tabAsk: 'ask',
    todayChart: "today's chart",
    addNewChart: 'add a new chart',
    myChart: 'my chart',
    addChart: 'add chart',
    otherCharts: 'other charts',
    otherChartsHint: 'e.g. friend, partner, family — add a label when you save.',
    noCharts: 'you have no saved charts yet.',
    noChartsHint: 'calculate a chart and save it with a label to see it here.',
    saveChart: 'save this chart',
    saveToMyChart: 'save as my chart',
    chartLabel: 'chart label',
    chartLabelPlaceholder: "e.g. friend, mom's chart",
    saved: 'saved',
    delete: 'delete',
    view: 'view',
    createdAt: 'saved',
    transitNewsTitle: 'upcoming aspects',
    transitNewsNoneInRange: 'none in search range',
    /** Inline verb phrase between transit sign and natal planet (see DashboardTransitNews). */
    transitNewsAspectVerb: {
      conjunction: 'conjuncting to',
      opposition: 'in opposition to',
      trine: 'trining to',
      sextile: 'sextiling to',
    },
    transitNewsNatal: 'natal',
    askPlaceholder: 'Ask anything…',
    askSend: 'Send',
    askError: 'Could not get a reply. Check ANTHROPIC_API_KEY in .env.',
    askEmpty: 'Ask a question above to chat.',
    astroCoinsTitle: 'wallet',
    astroCoinsLabel: 'astro coins',
    astroCoinsAmountLabel: 'amount (usd)',
    astroCoinsAmountPlaceholder: '10.00',
    astroCoinsBuyStripe: 'buy with card',
    astroCoinsAmountRequired: 'enter an amount (minimum $10 usd).',
    astroCoinsBuyStripeHint: '10 coins per $1 usd. minimum charge $10.',
    astroCoinsCheckoutError: 'could not start checkout. try again.',
    astroCoinsPurchaseSuccess: 'payment complete — your balance was updated.',
    astroCoinsPurchaseCancelled: 'checkout was cancelled.',
  },

  footer: {
    tagline: '',
    copyright: '© {year} future. made with ☾ in the usa. all rights reserved.',
    moonPhase: 'moon: {phase} · {days} days to {target} moon',
    moonTargetFull: 'full',
    moonTargetNew: 'new',
    links: [
      { label: 'predict', href: '/' },
      { label: 'current sky', href: '/today' },
      { label: 'create a chart', href: '/chart' },
      { label: 'influences', href: '/influence' },
      { label: 'compatibility', href: '/compatibility' },
      { label: 'dashboard', href: '/dashboard' },
    ],
  },

  compatibility: {
    title: 'compatibility',
    chart1: 'chart 1',
    chart2: 'chart 2',
    selectSaved: 'saved chart',
    calculateNew: 'calculate new',
    chooseChart: 'choose a chart',
    yourCharts: 'your saved charts',
    noCharts: 'No saved charts. Calculate one above or go to dashboard.',
    planetsInHouses: (name: string) => `${name}'s planets in the other's houses`,
    planet: 'planet',
    sign: 'sign',
    house: 'house',
    explanation: 'meaning',
    score: 'score',
    overall: 'overall compatibility',
    calculateCompatibility: 'calculate compatibility',
    compatibility: 'compatibility',
    scoreHigh: 'High',
    scoreMedium: 'Medium',
    scoreLow: 'Low',
  },

  home: {
    heroIcon: '✦',
    title: 'your cosmic blueprint',
    subtitle:
      'ancient wisdom meets the AI age',
    tagline: '',
    cta: 'calculate my chart',
    features: [
      { icon: '☉', label: 'learn about yourself' },
      { icon: 'handshake', label: 'check compatibility with others' },
    ],
  },

  predict,

  notFound: {
    title: 'page not found',
    message: 'This page drifted off the chart. Try heading back to your cosmic blueprint.',
    backHome: '← back to home',
  },

  privacy: {
    title: 'privacy policy',
    backHome: '← back to home',
    lastUpdated: 'last updated: march 2026',
    intro: 'future (“we”) respects your privacy. This policy describes how we collect, use, and protect your information when you use our services.',
    sections: {
      collection: 'information we collect',
      use: 'how we use your information',
      sharing: 'sharing your information',
      security: 'security',
      contact: 'contact us',
    },
  },

  terms: {
    title: 'terms of service',
    backHome: '← back to home',
    lastUpdated: 'last updated: march 2026',
    intro: 'Welcome to future. By using our services, you agree to these terms. Please read them carefully.',
    sections: {
      acceptance: 'acceptance of terms',
      use: 'use of the service',
      account: 'accounts',
      content: 'user content',
      contact: 'contact us',
    },
  },

  chart: {
    back: '← back',
    title: 'create a chart',
    titlePrefix: '✦',
    titleSuffix: '✦',
    tagline: '',
    back15m: '−15m',
    forward15m: '+15m',
    back1h: '−1 hr',
    forward1h: '+1 hr',
    see3D: 'see it in 3D',
    checkTransits: 'check transits',
    deleteChart: 'delete chart',
    transitsForMyChart: 'transits for my chart',
    transitsForSavedChart: (label: string) => `transits for ${label}`,
    transitsSubtitle: (dateLabel: string) => `current sky as of ${dateLabel}`,
    transitsTableNatal: 'natal',
    transitsTableTransits: 'transits',
    transitsGaussianTitle: 'transit–natal influences',
  },

  today: {
    title: 'current sky',
    subtitle: 'current transits in San Francisco',
    goToToday: 'go back to today',
    prevDay: '1 day before',
    nextDay: '1 day after',
    prevMonth: '1 month before',
    nextMonth: '1 month after',
    prevYear: '1 year before',
    nextYear: '1 year after',
  },

  solarSystem: {
    title: 'our solar system',
  },

  saveChart: {
    label: 'label for this chart',
    placeholder: "e.g. friend, partner's chart",
    button: 'save chart',
    saveToMyChart: 'save as my chart',
    calculateCompatibility: 'calculate a compatibility',
    saveWithLabel: 'Or save with a label',
    saving: 'saving…',
    success: 'chart saved.',
    signInToSave: 'sign in to save charts',
  },

  form: {
    sectionTitle: 'find your cosmic blueprint',
    dateLabel: 'date of birth',
    timeLabel: 'time of birth',
    timeNotKnown: 'time not known (use 12pm)',
    ascendantKnown: 'i know my ascendant',
    ascendantSignLabel: 'ascendant (rising sign)',
    cityLabel: 'birth city',
    cityNotKnown: 'city not known',
    utcLabel: 'utc offset — adjust if DST applies',
    utcPlaceholder: 'e.g. -5 or +1',
    submit: 'calculate my chart',
    calculating: 'calculating…',
    errors: {
      noDate: 'please enter your birth date.',
      noTime: 'please enter your birth time.',
      noCity: 'please search for and select a birth city.',
      invalidUtc: 'please enter a valid utc offset.',
      invalidYear: 'please use a birth date between -2000 and 2100.',
    },
  },

  chartOptions: {
    sectionTitle: 'add to chart',
    lilith: 'Lilith',
    juno: 'Juno',
    chiron: 'Chiron',
    northNode: 'North Node',
    southNode: 'South Node',
    lotOfFortune: 'Lot of Fortune',
    lotOfSpirit: 'Lot of Spirit',
    lotOfEros: 'Lot of Eros',
    lotOfVictory: 'Lot of Victory',
  },

  citySearch: {
    placeholder: 'e.g. san francisco',
    search: 'search',
    searching: 'searching…',
    foundPrefix: '✓',
  },

  planetTable: {
    planet: 'planet',
    sign: 'sign',
    degree: 'degree',
    house: 'house',
  },

  ascendant: {
    title: 'ascendant (rising sign)',
    risingSuffix: '— rising sign',
    mcLabel: 'mc (midheaven):',
    houseLabel: (n: number) => `house ${n}:`,
  },

  noAnglesNote:
    '(this chart has no ascendant - and other angles - since the birth time and/or birth place are needed to calculate these angles)',
  ascendantAngleUnknownNote:
    '(ascendant set at 15° since birth time and/or city are unknown)',
} as const;
